on: [push, pull_request]

name: CI

jobs:
  CI:
    name: Node ${{ matrix.node }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [20.19.0, 22]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}

      - name: Install dependencies
        run: npm install

      - name: Run TypeScript type checking
        run: npm run typecheck

      - name: Run ESLint
        run: npm run lint

      - name: Validate Prisma
        run: npx prisma generate && npx prisma validate

      - name: Build application
        run: npm run build
